### ISSUE TITLE
Add a (lightweight) package manager

### ISSUE THREAD

**Issue by xplshn** [portalinux-project/portalinux#7]
Hi! Saw this and I think it has potential, and I thought that it may even be a good base for my own project, for which I've been working on making components, and I plan to release some time this year or during 2025. One such project I've been developing is bigdl, which contrary to what its name suggest, its a very small binaries(statically linked) manager, it works the same way a normal package manager does, it can search, give you info about binaries, update, install, delete, and even run any of the programs in the repos without having to install them, I thought it'd be a great fit for this project.

https://github.com/xplshn/bigdl

There are currently 1550 binaries in the repos, and each month we add more, they are build using Github Actions, the majority of the binaries are compiled against Musl, so their size, even if statically linked is VERY small. I hope this doesn't come across as just spam, I really think we could collaborate and both of our projects would benefit from it.

There are other projects like mine out there ofc, and probably some that are much better. I used to offer a version of `bigdl` written in Shell that was only about 400 lines long, it had the same functionality minus the "update" option, you could take a look at that one and write something like that using the repo's of `bigdl` :)

`bigdl` weights 2megs in its upxed form, so, it could be an alias to this command, which lets you use `bigdl` without installing it: `wget -qO- "https://raw.githubusercontent.com/xplshn/bigdl/master/stubdl" | sh -s -- --help`

**Comment by cinnamonwolfy** [comment]
Hello there. While your package manager does sound nice, it won't work for PortaLinux due to our root filesystem size constraints (exactly 2MB or less as a gzip-compressed cpio, and i still have libraries to add) and your packaging methods (I mainly prefer packaging shared libraries, as that causes less duplication, and it's due to this trick why the root filesystem is so small in the first place). I have nothing against you forking the project and adding it yourself though, and I'm willing to help with that too, if you're interested (the codebase is a mess at the moment, so sorry in advance, if you decide to fork it. Also probably a good idea to let me help you with said fork, since there's no documentation yet).

**Comment by xplshn** [comment]
Okay, thanks for the insight! I think this is very promising, and a good candidate for building a full-fledged system that's small and suckless (I am kind of obsessed with bloat-free Unix oses, like PicoBSD).
